Add tests as a requirement for release.
defenseunicorns/uds-package-dubbd pull request #245
Opened 2023-06-07 17:39 UTC by bdfinst

2023-06-07 20:17 UTC, wirewc submitted a review, later dismissed
Reviewed with @bdfinst, look great!

2023-06-07 21:56 UTC, lucasrod16 requested changes

2023-06-07 21:56 UTC, lucasrod16 commented on .github/workflows/ci-on-push.yaml
I don't think we need a pipeline that only builds the packages. Building the packages in the test workflows should be sufficient for catching package creation errors. This duplicates that process

2023-06-07 21:56 UTC, lucasrod16 commented on .github/actions/create-bb-package/action.yaml
> +name: Create DUBBED Package
`DUBBED` --> `DUBBD`

2023-06-07 21:56 UTC, lucasrod16 commented on .github/actions/create-bb-package/action.yaml
> +description: Creates a DUBBED Zarf package for the requested path
`DUBBED` --> `DUBBD`

2023-06-07 21:56 UTC, lucasrod16 commented on .github/workflows/ci-on-push.yaml
> +name: DUBBED package CI
`DUBBED` --> `DUBBD`

2023-06-07 21:56 UTC, lucasrod16 commented on .github/workflows/ci-on-push.yaml
> +    name: Build DUBBED Distro
`DUBBED` --> `DUBBD`

2023-06-07 21:56 UTC, lucasrod16 commented on .github/workflows/ci-on-push.yaml
> +    name: Build DUBBED AWS Distro
`DUBBED` --> `DUBBD`

2023-06-07 22:03 UTC, lucasrod16 commented
We will also need to take a look at changing the name of the required status checks since we are changing the naming on them.

2023-06-08 11:47 UTC, bdfinst commented
> We will also need to take a look at changing the name of the required status checks since we are changing the naming on them.

Yes, that's a planned step after we merge this.

2023-06-08 12:56 UTC, merged