Refactors DUBBD-AWS IaC and introduces testing
defenseunicorns/uds-package-dubbd pull request #278
Opened 2023-06-13 20:59 UTC by UncleGedd

2023-06-20 14:38 UTC, justin-o12 commented on aws/loki/main.tf
> +  create_irsa               = var.create_irsa == true ? true : false
Is this used?  It looks like you reference the `var` below in the S3 module.

2023-06-20 14:38 UTC, justin-o12 commented on aws/loki/variables.tf
> +  description = "Create IRSA roles and plicy"
nit: typo

2023-06-20 15:24 UTC, bdfinst submitted a review, later dismissed
LGTM

2023-06-20 19:28 UTC, lucasrod16 requested changes

2023-06-20 19:28 UTC, lucasrod16 commented on .github/workflows/test-loki-bucket.yaml
> +  test-loki-bucket-zarf:
We may want to add a dependency on passing tests for the zarf package/deployment steps to run:

```yaml
    needs: test-loki-bucket-tf
```

2023-06-20 19:28 UTC, lucasrod16 commented on .github/workflows/test-loki-bucket.yaml
> +          zarf package create
We will need to add the `--confirm` flag here

2023-06-20 19:28 UTC, lucasrod16 commented on .github/workflows/test-loki-bucket.yaml
> +          zarf package deploy zarf-package-*.tar.zst \
We will need to add the `--confirm` flag here

2023-06-20 19:39 UTC, UncleGedd commented on .github/workflows/test-loki-bucket.yaml
> +          zarf package deploy zarf-package-*.tar.zst \
done!

2023-06-20 19:39 UTC, UncleGedd commented on aws/loki/variables.tf
> +  description = "Create IRSA roles and plicy"
done!

2023-06-20 19:39 UTC, UncleGedd commented on aws/loki/main.tf
> +  create_irsa               = var.create_irsa == true ? true : false
Fixed, using locals in that S3 module block now

2023-06-20 19:43 UTC, UncleGedd commented on .github/workflows/test-loki-bucket.yaml
> +  test-loki-bucket-zarf:
love it, adding

2023-06-20 21:16 UTC, justin-o12 approved these changes
All LGTM.  We can refactor where we download Terraform if we decide it's necessary.

2023-06-20 21:16 UTC, justin-o12 commented on aws/loki/zarf.yaml
> +  - name: download-terraform
We had discussed moving this back to `aws/zarf.yaml` so other, future IaC components do not have to include this.  If we don't do it in this PR, we can refactor this as we add the other components (e.g. EKS).

2023-06-20 21:23 UTC, lucasrod16 reviewed
@UncleGedd should we be implementing tests and zarf packaging for IaC modules in this repo?

It seems like we might benefit from doing those things in the source IaC repo, and only consume the published zarf package by importing the OCI package into our dubbd-aws package.

Thoughts?

2023-06-21 00:26 UTC, UncleGedd commented
> @UncleGedd should we be implementing tests and zarf packaging for IaC modules in this repo?
> 
> It seems like we might benefit from doing those things in the source IaC repo, and only consume the published zarf package by importing the OCI package into our dubbd-aws package.
> 
> Thoughts?

Yeah I see where you're coming from. A few thoughts:
1. OCI skeletons [don't work as expected](https://github.com/defenseunicorns/zarf/issues/1808) for components involving files
2. The terratest tests are IMO akin to a "unit test." In this case it's testing that our DUBBD-AWS-specific Terraform configs are working as expected (ie. the the Terraform code in `aws/loki`)
3. I don't think we should necessarily put a `zarf.yaml` in the TF modules, at least not othis one. IMO the `zarf.yaml` that we import from `aws/loki` should contain opinionated DUBBD configuration, as opposed to the less opinionated configus exposed in the TF modules

Def open to more thoughts/feedback on this though!

2023-06-21 12:54 UTC, UncleGedd commented on aws/loki/zarf.yaml
> +  - name: download-terraform
moved!

2023-06-21 15:14 UTC, justin-o12 submitted a review, later dismissed
LGTM

2023-06-21 15:23 UTC, mjnagel requested changes
CI is failing on `terraform output -raw irsa_role` in the AWS package (`Output "irsa_role" not found`) - I was trying to track down where/why and I think its related to moving `create_irsa` to a local?

2023-06-21 16:24 UTC, lucasrod16 commented
> > @UncleGedd should we be implementing tests and zarf packaging for IaC modules in this repo?
> > It seems like we might benefit from doing those things in the source IaC repo, and only consume the published zarf package by importing the OCI package into our dubbd-aws package.
> > Thoughts?
> 
> Yeah I see where you're coming from. A few thoughts:
> 
>     1. OCI skeletons [don't work as expected](https://github.com/defenseunicorns/zarf/issues/1808) for components involving files
> 
>     2. The terratest tests  in `aws/loki` are IMO akin to a "unit test." In this case it's testing that our DUBBD-AWS-specific Terraform configs are working as expected (ie. the the Terraform code in `aws/loki`)
> 
>     3. I don't think we should necessarily put a `zarf.yaml` in the TF modules, at least not this one. IMO the `zarf.yaml` that we import from `aws/loki` should contain opinionated DUBBD configuration, as opposed to the less opinionated configus exposed in the TF modules
> 
> 
> Def open to more thoughts/feedback on this though!

Thanks! Sounds good to me

2023-06-21 17:47 UTC, zachariahmiller commented
@UncleGedd isn't it outputting null for the irsa role because you are passing in `--set create_irsa=false` in the zarf command? That would make sense to me. Regardless, this is maybe a little complicated for what you are actually aiming to accomplish.  I'm in support of making a generic irsa role anyways. Also, how would you feel about adding the IaC tests you are trying to do here as an example/loki tests/loki inside the s3 bucket module or to be created irsa module?

2023-06-21 17:53 UTC, UncleGedd commented
> Regardless, this is maybe a little complicated for what you are actually aiming to accomplish.

Exactly this, the amount of workarounds I'm having to do to make this work feel off. 

 > adding the IaC tests you are trying to do here as an example/loki tests/loki
 
 I did add another test to the S3 module [here](https://github.com/defenseunicorns/terraform-aws-uds-s3/blob/98e72f23e1914b01012f751a213f7eda3c693cff/test/e2e/examples_test.go#L94), but if we refactor the IRSA into another module then I think this entire [commit](https://github.com/defenseunicorns/terraform-aws-uds-s3/commit/39a10229a7b2b4f2529d1ae1a72cec9b8a999f6e) could be reverted

2023-06-21 17:55 UTC, UncleGedd commented
> outputting null for the irsa role because you are passing in --set create_irsa=false in the zarf command?

Yes, I want it to:
- default to true
- but be false when testing and running the `aws/loki` CI
- but be true when running the e2e tests with the cluster

Again, WAY too complicated, all to get around some AWS components that are tightly coupled

2023-06-21 18:03 UTC, zachariahmiller commented
> > outputting null for the irsa role because you are passing in --set create_irsa=false in the zarf command?
> 
> Yes, I want it to:
> - default to true
> - but be false when testing and running the `aws/loki` CI
> - but be true when running the e2e tests with the cluster
> 
> Again, WAY too complicated, all to get around some AWS components that are tightly coupled and could be separated

Ah okay I think some of that context was lost on the mobile GitHub view. So yeah that would seem to require multiple zarf.configs to handle appropriately without adding multiple inputs and more testing logic. 

Only comment on the separate irsa module is that delivery is still consuming the s3 module that creates the irsa role so the implementation would need to still exist in the s3 bucket (call irsa module behind true/false) or would need to be a breaking change. I think this can be accomplished without issue and then just change the loki module to add irsa at the same level as the s3 bucket instead of nested inside, which _should_ facilitate what you are trying to accomplish. Still, if the tf output for the role name/arn is needed for the full deployment how do you plan on remedying that without getting into the same conditional rabbit hole?

2023-06-21 18:36 UTC, zachariahmiller commented
But doesn't it still need to be conditionally called in the loki module (based on full cluster or not full cluster test)? And as a product of that be conditionally producing an output (which granted you could control to be like "" if it wasn't present) 

I'm all for what you're suggesting if you think you have a way around the current issue. Maybe tomorrow you can show me what you mean real quick and it will just click. In the meantime, I'm good with this immediate change in direction.

2023-09-05 20:11 UTC, closed without merging

2023-09-05 20:11 UTC, UncleGedd commented
man this is old!