[WIP] 119 document local dev env setup and uds iac quick start as an onboarding resource
defenseunicorns/uds-package-dubbd pull request #279
Opened 2023-06-13 21:07 UTC by timblaktu

This PR (still a WIP) integrates a new `k3d-local` `zarf` package under the `k3d/` folder of `uds-package-dubbd`, and updates documentation for the `k3d` workflow, automating/dogfooding as much as possible with `zarf` tooling to maximise learning during onboarding.

Closes defense-unicorns/uds-package-dubbd#119.

2023-06-15 15:58 UTC, Racer159 commented on k3d/README.md
> +### [Install kubectl](https://kubernetes.io/docs/tasks/tools/#kubectlhttps://kubernetes.io/docs/tasks/tools/#kubectl)
`zarf tools kubectl` could be used (but raw kubectl can be nice too)

2023-06-15 15:58 UTC, Racer159 commented on k3d/local/README.md
> +[^1]: Noting that only global `zarf` options may be declared, and that `--confirm` is not a global option.
This isn't entirely true - sub items (like `package.create.output_directory`) can be configured too, but `--confirm` is explicitly excluded to encourage interactive deployments and reviews of packages (if it were hidden in a `zarf-config` file less experienced users may not get the option to review a deployment to see if they are deploying (or removing!) the correct package.

2023-06-15 15:58 UTC, Racer159 commented on k3d/local/zarf.yaml
> +          - cmd: 'k3d cluster delete ###ZARF_PKG_TMPL_K3D_CLUSTER_NAME###'
It may be worth noting somewhere that unlike many Zarf packages this doesn't actually work in an air gap and is thus for online dev only

2023-06-15 19:31 UTC, timblaktu commented on k3d/local/README.md
> +[^1]: Noting that only global `zarf` options may be declared, and that `--confirm` is not a global option.
Gotcha, thanks @Racer159. Then [this page](https://docs.zarf.dev/docs/the-zarf-cli/#using-a-config-file-to-make-cli-command-flags-declarative) needs to be corrected accordingly, no? It says:

> Users can configure the zarf init, zarf package create, zarf package deploy command flags, as well as any global flags, through a config file.

2023-06-15 20:29 UTC, timblaktu commented on k3d/README.md
> +### [Install kubectl](https://kubernetes.io/docs/tasks/tools/#kubectlhttps://kubernetes.io/docs/tasks/tools/#kubectl)
@Racer159 thanks for heads-up on this. Are the `zarf tools` like `kubectl` statically embedded in the zarf binary? If so, how does zarf decide which version to use? Sorry if this is documented somewhere, I couldn't find it. [The cli command docs](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_tools_kubectl) imply "i just works" without saying _how_.

..but in general, I want to leverage any tools embedded in zarf to minimize dependencies and config/setup steps. Thanks again for the hint.

2023-06-15 22:04 UTC, timblaktu commented on k3d/README.md
> +### [Install kubectl](https://kubernetes.io/docs/tasks/tools/#kubectlhttps://kubernetes.io/docs/tasks/tools/#kubectl)
@wayne i see in [the code](https://github.com/defenseunicorns/zarf/blob/1aeae1b584ec36cd3ce252358c8ccbeabbce0dfe/src/cmd/tools/kubectl.go#L11) that zarf imports the upstream k8s cli code, so i think i answered the question about embedding, only thing remaining is figuring out the relationship between a zarf version and k8s version.

2023-06-15 22:55 UTC, timblaktu commented on k3d/local/zarf.yaml
> +          - cmd: 'k3d cluster delete ###ZARF_PKG_TMPL_K3D_CLUSTER_NAME###'
@racer159 to work in an airgap, this would need to include the container registry init component, and push the k3s images to it for k3d to use, right? Anything else?

2023-06-16 14:46 UTC, MxNxPx commented on k3d/values/local-dev.yaml
> +      install: false
is there a reason this is being set to false?

2023-06-16 14:48 UTC, MxNxPx commented on k3d/zarf.yaml
>    # x-release-please-end
this would need to be added to the https://github.com/defenseunicorns/uds-package-dubbd/blob/main/release-please-config.json to be versioned alongside the other packages

2023-06-16 14:55 UTC, mjnagel submitted a review, later dismissed
Can you rebase this + resolve conflicts to make sure things are up to date with `main`?

2023-06-16 14:57 UTC, MxNxPx commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
renovate should auto PR newer zarf versions if you add a comment right above the zarf_version line like this - https://github.com/defenseunicorns/uds-package-dubbd/blob/main/.github/actions/create-bb-package/action.yaml#L36

2023-06-16 15:04 UTC, timblaktu commented on k3d/values/local-dev.yaml
> +      install: false
@MxNxPx not sure, I took these lines from a Slack thread a few weeks ago. I believe they came from @mjnagel ?

2023-06-16 15:07 UTC, timblaktu commented on k3d/zarf.yaml
>    # x-release-please-end
@MxNxPx I believe this is now in place after merging main. Can you confirm?

2023-06-16 15:08 UTC, timblaktu commented
> Can you rebase this + resolve conflicts to make sure things are up to date with `main`?

@MxNxPx I didn't rebase, but I did merge main, resolving conflicts around the time you sent this. Is rebasing necessary since we're squashing commits on merge?

2023-06-16 15:09 UTC, MxNxPx commented on k3d/README.md
> +export REGISTRY2_PASSWORD="YOUR-PASSWORD-HERE"
typo here perhaps?

2023-06-16 15:11 UTC, MxNxPx commented on k3d/values/local-dev.yaml
> +      install: false
got it - then i think we would want to remove those lines

2023-06-16 15:12 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
I see, thanks. This reminds me that all my testing was done using the zarf commands directly, so I need to go back and integrate/test a new k3d-local make target. 

What I need here, regardless of whether zarf is run directly or in renovate container, is to pick up the _actual_ version of the zarf process running. Do you know how to fetch that from the env? I figured it would exist as a `PKG_TMPL_*` kind of like `ARCH` is but haven't been able to find it yet.

2023-06-16 15:14 UTC, mjnagel commented
> I didn't rebase, but I did merge main, resolving conflicts around the time you sent this. Is rebasing necessary since we're squashing commits on merge?

@timblaktu as long as main is merged & conflicts resolved we should be totally fine - no need for a true rebase :)

2023-06-16 15:15 UTC, MxNxPx commented on k3d/zarf.yaml
>    # x-release-please-end
i was looking at the wrong file also - my bad!

2023-06-16 15:17 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@MxNxPx that renovate comment is in a GH action workflow. Where would I put that in my case, i.e. running all this via make?

2023-06-16 15:25 UTC, MxNxPx commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@timblaktu - renovate itself will cut a PR to update that version based on the comment in any yaml.  although the `v` prefix` in the version would need to be removed in order to have renovate regex to match it.

2023-06-16 15:51 UTC, mjnagel commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
I might just be confused here - when you say you are running this via make...was that just for local testing or did you intend to push up a makefile?

2023-06-16 16:37 UTC, timblaktu commented on k3d/values/local-dev.yaml
> +      install: false
These lines have been removed in latest commit. Thanks!

2023-06-16 16:55 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@MxNxPx I'm referring to the top-level Makefile in uds-package-dubbd. There aren't any make targets for k3d-local yet (to my knowledge), and what I'm saying is that up till now I've NOT been using make to test k3d-local, instead just calling zarf directly to create/deploy/remove it. As such, I'm not exercising renovate at all WRT k3d-local.

I'm planning to simply wrap these zarf calls in new make targets in the top-level Makefile in uds-package-dubbd, so that we leverage renovate's ability to handle tool versioning.

My TODO that started this thread is there bc currently this k3d-local package needs to know what version of zarf is being used to create the package, bc it downloads the corresponding init package and refers to it by filename which includes version. Since the zarf_version here is tracked as a create-time `PKG_TMPL` zarf template, essentially a hard-coded constant in the zarf-config.yaml, there's nothing to ensure this version is "correct" for a given build environment.

I had assumed the easiest thing to do would be to automatically set the version template value using some available zarf environment variable, but I can't find support for this anywhere. (kind of like how you can fetch the current ARCH of the current package using `###ZARF_PKG_ARCH###`..)

I see now at least 2 other solutions:

1. `make k3d-local` can simply write `zarf version` into `zarf-config.yaml` on `zarf package create`
2. do away with the handling and need-to-know of zarf version altogether, since I'm now downloading the init package using `zarf tools download-init`, which:
    * automatically fetches the correctly-versioned init pkg, and 
    * accepts `-o init_pkg_filename` arg, which means I can just refer to the file as versionless `init` at both `create` and `deploy`-time.

2 is simpler, unless we actually need to know the version for some other reason. I'm guessing not, and that if so, I should be able to wrap that need in a zarf call. `zarf` seems designed to always to the right thing, version-wise.

2023-06-16 17:02 UTC, mjnagel commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
Oh, I honestly did not realize there was a makefile in this repo - it looks like it hasn't been touched in a while and honestly could probably just be removed in favor of our docs that guide people through using their own `zarf` binary and specific commands to create/deploy. I don't think the make targets are currently referenced anywhere/used in CI.

For what its worth I like option 2 you mentioned - it keeps it simple and removes the need for version.

2023-06-16 17:12 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@palassis furthermore, in the bigger picture we need to remember that this k3d-local package is for dubbd development. As such, in addition to ensuring the deployed init pkg == the current zarf version, it needs to *enforce* that this is identical to the zarf version being used by the top-level dubbd package.

To that end, I believe 2 above is the way to go - remove any dependency/usage/consciousness of the zarf version being used.

2023-06-16 17:20 UTC, timblaktu commented on k3d/README.md
> +export REGISTRY2_PASSWORD="YOUR-PASSWORD-HERE"
Good catch, I copied this from the main k3d README and probably vim-botched it somehow. ;-) @MxNxPx how do you feel about me replacing these instructions for container reg authN with the way I did it above in the GitHub AuthN section?

2023-06-16 17:44 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@mjnagel thanks. I also got confirmation from @lucasrod16 that the Makefile wasn't being used in CI. I also see that we are not using the build harness in CI. Is that you're understanding?

Yes, I plan to implement 2 above.

2023-06-16 19:18 UTC, timblaktu commented on k3d/local/zarf-config.yaml
> +      zarf_version: v0.27.0
@MxNxPx @mjnagel @lucasrod16 my latest commits have removed the Makefile and "zarf-version-consciousness" from the k3d-local package..

2023-06-20 16:03 UTC, timblaktu commented on k3d/local/README.md
> +[^1]: Noting that only global `zarf` options may be declared, and that `--confirm` is not a global option.
Tracked here: https://github.com/defenseunicorns/zarf/issues/1833

2023-06-20 16:05 UTC, timblaktu commented on k3d/README.md
> +export REGISTRY2_PASSWORD="YOUR-PASSWORD-HERE"
This was resolved in commits last week which consolidated docs about authN to container registries.

2023-06-21 13:46 UTC, wirewc approved these changes

2023-06-21 14:25 UTC, mjnagel commented on k3d/README.md
> +1. Login to your GitHub Account with access to the `defenseunicorns` organization.
nit: `defenseunicorns` org access isn't required is it? All the images/artifacts pulled here should be public to anyone with a github account?

2023-06-21 14:31 UTC, mjnagel commented on k3d/README.md
>  zarf package deploy oci://ghcr.io/defenseunicorns/packages/dubbd-k3d:0.0.1-amd64 --oci-concurrency=15
Might be worth updating this comment/command to reflect the latest tag and/or link to release page to get the latest.

2023-06-21 14:34 UTC, timblaktu commented
> Added comments - I think this approach is OK, though again Make may be better for local development since while Zarf can be a shell wrapper, Make was designed for it.

Agreed, this was an odd application of `zarf` that was done by a curious newbie. If the UDS team decides to use `make` again,  this "zarfification" of  k3d-local pkg could easily be moved to a recipe there.

2023-06-21 14:38 UTC, timblaktu commented on k3d/README.md
> +1. Login to your GitHub Account with access to the `defenseunicorns` organization.
@mjnagel correct, ghcr isn't required to deploy the k3d cluster. These are considered consolidated instructions for deploying dubbd on local k3d cluster, and that's why ghcr is mentioned here.

2023-06-21 14:40 UTC, timblaktu commented on k3d/README.md
> +1. Login to your GitHub Account with access to the `defenseunicorns` organization.
@mjnagel I get your point now... :/ Yes, I suppose the defenseunicorns org is irrelevant here. I'll remove.

2023-06-21 14:41 UTC, mjnagel requested changes

2023-06-21 14:41 UTC, mjnagel commented on k3d/local/zarf.yaml
> +                (set -x; zarf tools download-init -o downloads)
`zarf tools download-init` will always download based on the system architecture, which might not match the hardcoded package architecture (amd64). I was trying to use `-a amd64` which should be a global flag but it doesn't seem to be respected.

In my case (on an ARM mac) I was seeing this error:
```
  ✔  Downloaded https://github.com/defenseunicorns/zarf/releases/download/v0.27.1/zarf-init-arm64-v0.27.1.tar.zst                                                                                                                         
     cp: downloads/zarf-init-amd64-v0.27.1.tar.zst: No such file or directory                                                                                                                                                             
     ls: *.zst: No such file or directory                                                                                                                                                                                                 
     downloads:                                                                                                                                                                                                                           
     total 1048704                                                                                                                                                                                                                        
     -rw-r--r--  1 mjnagel  staff   497M Jun 21 08:37 zarf-init-arm64-v0.27.1.tar.zst                                                                                                                                                     
     drwx------  3 mjnagel  staff    96B Jun 21 08:36 .                                                                                                                                                                                   
     drwxr-xr-x  8 mjnagel  staff   256B Jun 21 08:36 ..                                                                                                                                                                                  
     ERROR:  Failed to create package: unable to add component: unable to run component before action: command                                                                                                                            
             "F="downloads/zarf-init-amd64-$(zarf version).tar.zst";; i..." failed after 0 retries
```

2023-06-21 14:52 UTC, timblaktu commented on k3d/README.md
>  zarf package deploy oci://ghcr.io/defenseunicorns/packages/dubbd-k3d:0.0.1-amd64 --oci-concurrency=15
Done.

2023-06-21 14:55 UTC, timblaktu commented on k3d/local/zarf.yaml
> +                (set -x; zarf tools download-init -o downloads)
@mjnagel arch is declaratively hard-coded in zarf-config.yaml to amd64, this is why the instructions don't include `-a`. I suppose the action item here is to update the README to indicate this only works on amd64.

2023-06-21 14:57 UTC, mjnagel commented on k3d/local/zarf.yaml
> +                (set -x; zarf tools download-init -o downloads)
If we want to document as a limitation I'm fine with that. In general I would expect that the package should be able to be built on any architecture, then only deployed on `amd64` (DUBBD works this way). In this case that is not possible because init will be downloaded based on the system architecture.

2023-06-21 15:50 UTC, mjnagel commented on k3d/README.md
> +Currently, Package creation is currently only supported on amd64 systems, due to a bug that `zarf tools download-init` ignores -a/--architecture` args, and always uses the system architecture._
```suggestion
```
I think this is duplicative of the above?

2023-06-21 15:51 UTC, mjnagel approved these changes
LGTM otherwise - thanks for all the work on this @timblaktu 🥳

2023-06-21 16:02 UTC, mjnagel approved these changes

2023-06-21 16:23 UTC, mjnagel submitted a review, later dismissed

2023-06-21 17:46 UTC, timblaktu commented
> LGTM otherwise - thanks for all the work on this @timblaktu partying_face

@mjnagel @wirewc would you mind approving? The PR is still blocked requiring review.

2023-06-21 17:58 UTC, wirewc commented
@timblaktu I'm looking at something quickly before approving.

2023-06-21 18:09 UTC, wirewc approved these changes
:+1:

2023-06-21 20:53 UTC, merged