feat: add external-dns
defenseunicorns/uds-package-dubbd pull request #346
Opened 2023-06-28 20:52 UTC by MxNxPx

2023-07-07 13:33 UTC, UncleGedd commented on aws/route53-policy/README.md
> +# Loki
I may be missing something, but why do we have Loki docs in the route53 folder?

2023-07-07 13:35 UTC, justin-o12 commented on aws/route53-policy/README.md
> +Terraform for deploying resources necessary for Loki
nit: Title and describe these for the Route 53 policy.

2023-07-07 13:35 UTC, justin-o12 commented on aws/route53-policy/main.tf
> +        "arn:aws:route53:::hostedzone/*"
I recommend updating this arn to use the partition like this https://github.com/defenseunicorns/uds-package-dubbd/blob/65c5f1fdc0193291bb68dd9d75e14c27bb7da0ef/aws/loki/main.tf#L27C36-L27C75

2023-07-07 15:51 UTC, justin-o12 approved these changes
Great work, palassis!

2023-07-07 16:11 UTC, MxNxPx commented on aws/route53-policy/main.tf
> +        "arn:aws:route53:::hostedzone/*"
good call @justin-o12 !

updated now:
https://github.com/defenseunicorns/uds-package-dubbd/blob/add-dns/aws/route53-policy/main.tf#L40-L42

2023-07-07 16:12 UTC, MxNxPx commented on aws/route53-policy/README.md
> +# Loki
@UncleGedd - meant to update but didn't, thanks for catching.

updated now:
https://github.com/defenseunicorns/uds-package-dubbd/blob/add-dns/aws/route53-policy/README.md

2023-07-07 16:12 UTC, MxNxPx commented on aws/route53-policy/README.md
> +Terraform for deploying resources necessary for Loki
updated now:
https://github.com/defenseunicorns/uds-package-dubbd/blob/add-dns/aws/route53-policy/README.md

2023-07-07 17:02 UTC, UncleGedd submitted a review, later dismissed
🚀 🦄

2023-07-07 17:55 UTC, justin-o12 submitted a review, later dismissed
:rocket:

2023-07-07 18:37 UTC, mjnagel requested changes
Feel free to dismiss any of these that you don't think need addressing before merging.

2023-07-07 18:37 UTC, mjnagel commented on aws/dubbd-aws/zarf.yaml
> +              terraform init -force-copy \
We probably want all of these tf commands to be `../terraform` to ensure we are using the embedded tf since we switched loki to use it.

2023-07-07 18:37 UTC, mjnagel commented on aws/dubbd-aws/zarf.yaml
> +        - cmd: echo "${ZARF_VAR_STATE_KEY_PREFIX}-${ZARF_VAR_STATE_KEY}"
This is definitely a nitpick but is there a reason we need the state_key_prefix to be its own zarf var? Versus just hardcoding here?

2023-07-07 18:37 UTC, mjnagel commented on aws/uds-core-aws/zarf.yaml
> +  - name: route53-policy-pre
All the (new) pieces here should really just be imports from `aws/dubbd-aws` I thinks. Otherwise any changes to route53 need to be copied here as well. 

I know this isn't the case with the DUBBD pieces (although it should be), but I think as we add new pieces it makes sense to just import.

2023-07-07 18:49 UTC, mjnagel commented on release-please-config.json
> +        "aws/external-dns/zarf.yaml",
Missed this in my earlier review - do we actually want to release external dns as a thing on its own? We aren't doing that with eks, cloudtrail, loki, so I don't think we would want to here either?

2023-07-07 18:54 UTC, MxNxPx commented on aws/uds-core-aws/zarf.yaml
> +  - name: route53-policy-pre
agreed - opened https://github.com/defenseunicorns/uds-package-dubbd/issues/378

2023-07-07 18:55 UTC, MxNxPx commented on aws/dubbd-aws/zarf.yaml
> +        - cmd: echo "${ZARF_VAR_STATE_KEY_PREFIX}-${ZARF_VAR_STATE_KEY}"
agreed - opened https://github.com/defenseunicorns/uds-package-dubbd/issues/377

2023-07-07 19:28 UTC, MxNxPx commented on aws/dubbd-aws/zarf.yaml
> +              terraform init -force-copy \
good catch @mjnagel!

updated here:
https://github.com/defenseunicorns/uds-package-dubbd/blob/add-dns/aws/dubbd-aws/zarf.yaml#L175

2023-07-07 19:37 UTC, MxNxPx commented on release-please-config.json
> +        "aws/external-dns/zarf.yaml",
imho, i would want any `zarf.yaml` in this repo to be co-versioned.  i would agree to not publish the oci artifact for all the `zarf.yaml`'s as they aren't intended for use in that standalone manner.  planning to leave this in here and in a subsequent PR to update the release-please-config.json for the other `zarf.yaml` files.

2023-07-07 21:24 UTC, mjnagel submitted a review, later dismissed

2023-07-10 17:31 UTC, mjnagel commented on README.md
> +  - [dubbd-aws](./aws/dubbd-aws) - _DUBBD pakcage for aws (imports DUBBD base)_
```suggestion
  - [dubbd-aws](./aws/dubbd-aws) - _DUBBD package for aws (imports DUBBD base)_
```
[ci skip]? 🙃

2023-07-10 17:53 UTC, MxNxPx commented on README.md
> +  - [dubbd-aws](./aws/dubbd-aws) - _DUBBD pakcage for aws (imports DUBBD base)_
good catch - updated now.

2023-07-10 17:53 UTC, MxNxPx commented on README.md
> +  - [uds-core-aws](./aws/uds-core-aws) - _UDS core pakcage for aws (imports DUBBD aws)_
good catch - updated now.

2023-07-10 17:54 UTC, mjnagel approved these changes
:shipit: LGTM!

2023-07-10 17:54 UTC, merged