docs: add adr for disabling kiali operator
defenseunicorns/uds-package-dubbd pull request #493
Opened 2023-08-10 01:01 UTC by MxNxPx

addresses https://github.com/defenseunicorns/uds-package-dubbd/issues/491

2023-08-10 01:13 UTC, corang commented
Is skipping the operator and deploying kiali directly an option here? I think it still provides value

2023-08-10 01:45 UTC, MxNxPx commented
> Is skipping the operator and deploying kiali directly an option here? I think it still provides value

@corang - i hope that i am wrong... but i think @mjnagel had said BB doesn't have straight Kiali available

2023-08-10 01:52 UTC, mjnagel commented
@MxNxPx @corang BB does not publish a Kiali only chart, but the image would be the same one from Ironbank. It would mean we have to maintain our own chart with the BB integration pieces (or some 🌶️ magic to do that). Not totally infeasible but not as easy as adding a new gitrepo in our values.

2023-08-10 16:08 UTC, mjnagel commented on docs/adrs/0003-disable-kiali-operator-for-dubbd.md
> +* Best practices (from delivery experience)
Recommend we remove "delivery" wording (here and a few other spots below) and switch to user/customer to use more public facing language here.

2023-08-11 15:00 UTC, blancharda commented
Some end users have expressed concern over (potentially) losing access to the tool.

They described it as a "single pane of glass" view for monitoring the current state of their deployments and in-cluster communication, which they use regularly during upgrade cycles to monitor health.

My preference would be to leave it in place until we have an alternative recommendation for installing it ad-hoc.
(And perhaps doing a broader user survey to better understand more end-user's usage patterns.)

That said, the underlying resource usage problem is still a problem..
+1 for @corang's suggestion above.. the [kiali-server chart](https://kiali.io/docs/installation/installation-guide/install-with-helm/) may be a potential starting point.

2023-08-16 19:10 UTC, MxNxPx commented on docs/adrs/0003-disable-kiali-operator-for-dubbd.md
> +* Best practices (from delivery experience)
good call @mjnagel - replaced with the more general "platform" verbiage via [this commit](https://github.com/defenseunicorns/uds-package-dubbd/commit/50d6fcaf5e68c199de85eb1033101feda8f0825d)

2023-08-16 19:19 UTC, corang requested changes
Leaving it in is fine, but we still haven't addressed the problem. Kiali is still of no value if it never gets deployed by the operator

2023-08-16 19:20 UTC, corang commented
> Leaving it in is fine, but we still haven't addressed the problem. Kiali is still of no value if it never gets deployed by the operator

It's probably the most work out of all the issues but it seems like deploying kiali ourself directly without the operator solves the most problems.

2023-08-16 19:21 UTC, corang commented
> > Leaving it in is fine, but we still haven't addressed the problem. Kiali is still of no value if it never gets deployed by the operator
> 
> It's probably the most work out of all the issues but it seems like deploying kiali ourself directly without the operator solves the most problems.

Or as a bandaid just bump the memory limit a few gigs for now and mark it as a known issue

2023-08-16 19:24 UTC, MxNxPx commented
> > > Leaving it in is fine, but we still haven't addressed the problem. Kiali is still of no value if it never gets deployed by the operator
> > 
> > 
> > It's probably the most work out of all the issues but it seems like deploying kiali ourself directly without the operator solves the most problems.
> 
> Or as a bandaid just bump the memory limit a few gigs for now and mark it as a known issue

@corang - agreed.  i have opened [this ticket](https://github.com/defenseunicorns/uds-package-dubbd/issues/505) to address separately from this ADR.

2023-08-16 19:27 UTC, mjnagel approved these changes

2023-08-16 19:29 UTC, corang approved these changes
Given the other ticket this is fine

2023-08-17 18:59 UTC, merged