feat: add more preflight checks
defenseunicorns/uds-package-dubbd pull request #517
Opened 2023-08-22 14:40 UTC by noahpb

addresses concerns for dubbd in https://github.com/defenseunicorns/uds-cli/issues/4

2023-08-22 18:36 UTC, mjnagel commented on defense-unicorns-distro/scripts/preflight.sh
> +fi
Does it make sense to reverse the order of these two checks? And maybe the health one? Confirm we have a kubeconfig (and maybe confirm cluster health) before checking version?

2023-08-22 20:56 UTC, MxNxPx approved these changes
:ship: :it:

2023-08-22 21:13 UTC, MxNxPx requested changes
looking good after you make some of the changes we discussed where the commands run in the component before action always return a 0 exit status and is handled with logic in the script after the fact.

2023-08-23 14:42 UTC, MxNxPx submitted a review, later dismissed

2023-08-23 18:16 UTC, mjnagel approved these changes
:shipit:

2023-08-23 18:24 UTC, merged