Add Velero for RKE2
defenseunicorns/uds-package-dubbd pull request #636
Opened 2023-11-29 22:20 UTC by blancharda

Enabling velero with a default config. Adding variables to configure object storage.
Addresses #635 

NOTE:
Adds an assumption that object storage is available for RKE2 deployments.

2023-11-30 18:31 UTC, MxNxPx requested changes

2023-11-30 18:31 UTC, MxNxPx commented on rke2/values/rke2-velero.yaml
> +    enabled: true
@blancharda i assume we will want this to be the toggle point:
```yaml
addons:
  velero:
    enabled: "###ZARF_VAR_VELERO_ENABLED###"
```

2023-11-30 18:31 UTC, MxNxPx commented on rke2/zarf.yaml
> +    default: "true"
thinking we may want to conditionally set this value, something like: https://github.com/defenseunicorns/uds-package-external-dns/blob/37d8850c47189c09d9d914a7c5c4dbff287489e0/zarf.yaml#L53-L63

so default to false unless `VELERO_S3_BUCKET` is set.

2023-11-30 19:16 UTC, blancharda commented on rke2/zarf.yaml
> +    default: "true"
I'm not sure I love the idea of components being toggled on (or off) dynamically.
Bigbang itself occasionally does this, and it can be quite confusing to debug.

If I've explicitly configured `VELERO_ENABLED = "false"` I don't think I would want an action in the Zarf package to override that at deploy time.

That said, I do like the idea of some kind of pre-flight check or warning though if  `VELERO_ENABLED = "true"` and the bucket info is unset 🤔

2023-11-30 19:18 UTC, blancharda commented on rke2/zarf.yaml
> +    default: "true"
I could also be talked into the default being false for now.. but I do think it is something we are going to want in almost every (if not all) environments eventually.

2023-11-30 19:50 UTC, MxNxPx commented on rke2/zarf.yaml
> +    default: "true"
@blancharda - good points!  i was thinking more about not impacting folks who might already be using the dubbd-rke2 package rather than the confusion this could cause on deployment.

thinking through this a bit more, if the default was false, then zarf wouldn't include it on package create time.  also if it was true and at deploy time it was changed to false, at package create time it will build out the zarf actions to wait on the helmrelease to be ready, and fail at deploy time.  :thinking:

2023-11-30 20:12 UTC, blancharda commented on rke2/zarf.yaml
> +    default: "true"
The zarf actions could be conditioned in a way to check for the component being enabled.. but the package create time setting is a real problem...

We may just need to enable it "permanently" by setting `enabled: true` 🤔
(Technically someone could still disable it at deploy time via custom bigbang values).

2023-11-30 22:56 UTC, blancharda commented on rke2/zarf.yaml
> +    default: "true"
Upon further discussion, I think the path forward here is to require object storage as a pre-requisite to deployment for the RKE2 distro, mirroring the behavior of the AWS distro.

In CI we can deploy S3 buckets (yes.. it's a little funny for the RKE2 "on prem" distro, but will allow for some re-use with the AWS package CI code).

For dev work and actual installs, users will be expected to provide a solution prior to the DUBBD install.

2023-12-01 22:51 UTC, blancharda commented on .github/test-infra/rke2/main.tf
> +################ S3 Bucket(s) #################
Could be moved to a local module to make creating the loki bucket easier

2023-12-04 23:46 UTC, mjnagel commented on rke2/zarf.yaml
> +        executable: true
We don't have a preflight for this on the AWS DUBBD...but I'm not sure if that's because we forgot or because its unnecessary? If a var is not defaulted and prompt is not false it should prompt for it, correct? Or does that behavior change with `--confirm`?

2023-12-05 14:58 UTC, blancharda commented on rke2/zarf.yaml
> +        executable: true
I just tested to double check..
When using `--confirm` the deployment will continue with empty strings `('')` in the variables, even when `prompt: true` is set in the variable declaration. Test values below if you want to confirm..

Zarf var declaration:
```
variables:
  - name: CHECKING
    prompt: true
    description: just checking..
    #default: intentionally empty
 ```

* Create the zarf pakcage: `zarf package create .`
* Deploy the package (no confirm): `zarf package deploy zarf*.zst`
  * Pauses and prompts the user as expected
* Deploy the package with confirm: `zarf package deploy zarf*.zst --confirm`
  * Deploys the package with output that indicates an empty variable
  ```
  ...
  variables:  deployment-specific values that are set on each package deployment

  - name: CHECKING  currently set to '' (default)
    description: just checking..
    prompt: true
  ...
  ```
  
  I think we should leave in the preflight if we want setting the vars to be enforced.

2023-12-05 15:03 UTC, blancharda commented on rke2/values/rke2-velero-s3.yaml
> +            eks.amazonaws.com/role-arn: "###ZARF_VAR_VELERO_S3_AWS_ROLE_ARN###"
Agreed, the var is already gone. Copy/pasta strikes again. This config isn't even using the key/secret 🙈 

I'll push an update.

2023-12-05 15:15 UTC, mjnagel commented on rke2/values/rke2-velero-s3.yaml
> +              region: "###ZARF_VAR_VELERO_S3_AWS_REGION###"
Missed this earlier but these all have `S3` in the name - the vars in the zarf yaml and preflight check do not. I'm not sure things are being passed in properly?

2023-12-05 16:40 UTC, blancharda commented on rke2/values/rke2-velero-s3.yaml
> +              region: "###ZARF_VAR_VELERO_S3_AWS_REGION###"
🤦 
I really should have just started a new PR.

2023-12-06 00:43 UTC, MxNxPx commented on rke2/values/rke2-velero-s3.yaml
> +              s3Url: http://minio.minio.svc.cluster.local:9000
@blancharda - wondering if we would want to consider making these zarf vars also? 

i am good with merging as-is as the dubbd override values can also be used to change these.

2023-12-06 00:46 UTC, MxNxPx requested changes

2023-12-06 00:46 UTC, MxNxPx commented on rke2/zarf.yaml
> +          - values/rke2-velero-s3.yaml
would want this file to be above the `add-dubbd-values.yaml` so it can override anything set.

2023-12-06 14:26 UTC, blancharda commented on rke2/zarf.yaml
> +          - values/rke2-velero-s3.yaml
Interesting, I was thinking of that file as the base, and the other files as the overlays, but if the convention is the other way that's an easy enough swap :)

2023-12-06 14:28 UTC, blancharda commented on rke2/values/rke2-velero-s3.yaml
> +              s3Url: http://minio.minio.svc.cluster.local:9000
Good catch!
That should definitely be exposed, otherwise anyone using this in practice (and not using minio) would have to completely replace the Velero config. 

I sort of expect that to be necessary anyways, but it would be good to variablize this out so that there was potential reuse of the "default" config at least..

2023-12-08 20:08 UTC, merged